version: '3.8'

services:
  # Override app service for development
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nestjs-esb-dev
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: esb_db
    volumes:
      # Mount source code for hot reloading
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "4000:4000"
      - "9229:9229" # Debug port

  # Override database for development (with exposed ports)
  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esb_db

  # Development tools
  adminer:
    image: adminer
    container_name: esb-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - esb-network
    depends_on:
      - db
